pr:
  autoCancel: true

jobs:
- job: 'Linux'
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
      Python312:
        python.version: '3.12'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add Conda to PATH'

  - bash: |
      set -e # Exit script if any command fails
      conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
      conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
      conda config --set always_yes yes --set changeps1 no

      # Create the environment
      conda create -n hicexplorer -c conda-forge -c bioconda python=$(python.version) --file requirements.txt
      
      # Install other dependencies directly into the inactive environment
      conda install -n hicexplorer -c conda-forge -c bioconda \
        pytest \
        flake8 \
        pytest-xdist \
        pytest-forked \
        nose \
        pathlib \
        configparser
        
      # Run pip install using the python from within the environment
      conda run -n hicexplorer pip install . --no-deps
    displayName: 'Install Dependencies'

  - bash: |
      conda run -n hicexplorer flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F401,F403,E402,F999,F405,E712,W504
    displayName: 'Linting'

  - bash: |
      conda run -n hicexplorer py.test hicexplorer/test/test_pytest_collected_items.py --doctest-modules --capture=sys
      conda run -n hicexplorer py.test hicexplorer --doctest-modules --ignore=hicexplorer/test/
    displayName: 'Doc Test and Number of Cases'

  - bash: |
      conda run -n hicexplorer py.test hicexplorer/test/general/ --doctest-modules --capture=sys -n 4 --ignore=hicexplorer/test/general/test_hicTADClassifier.py --ignore=hicexplorer/test/general/test_hicTrainTADClassifier.py
    displayName: 'Pytest'

  - bash: |
      conda run -n hicexplorer py.test hicexplorer/test/general/test_hicTADClassifier.py
      conda run -n hicexplorer py.test hicexplorer/test/general/test_hicTrainTADClassifier.py
    displayName: 'Pytest TAD Classifier'

- job: 'OSX'
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-latest'
  variables:
    CONDA: /Users/runner/miniconda3
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
      Python312:
        python.version: '3.12'

  steps:
  # This step is essential and must come first.
  - bash: |
      set -e
      # curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
      curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh  -o $HOME/miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda3
      echo "##vso[task.prependpath]$HOME/miniconda3/bin"
    displayName: 'Install Miniconda'
    
  - bash: |
      set -e # Exit script if any command fails
      conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
      conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
      conda config --set always_yes yes --set changeps1 no
      
      # Create the environment from the requirements file
      conda create -n hicexplorer -c conda-forge -c bioconda \
        python=$(python.version) \
        --file requirements.txt
      
      # Install other dependencies directly into the new environment
      conda install -n hicexplorer -c conda-forge -c bioconda \
        pytest \
        flake8 \
        pytest-xdist \
        pytest-forked \
        nose \
        pathlib \
        configparser

      # Run pip install using the python from within the environment
      conda run -n hicexplorer pip install . --no-deps
    displayName: 'Install Dependencies'

  - bash: |
      conda run -n hicexplorer flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F401,F403,E402,F999,F405,E712,W504
    displayName: 'Linting'

  - bash: |
      conda run -n hicexplorer py.test hicexplorer/test/test_pytest_collected_items.py --doctest-modules --capture=sys
      conda run -n hicexplorer py.test hicexplorer --doctest-modules --ignore=hicexplorer/test/
    displayName: 'Doc Test and Number of Cases'

  - bash: |
      conda run -n hicexplorer py.test hicexplorer/test/general/ --doctest-modules --capture=sys -n 4 --ignore=hicexplorer/test/general/test_hicTADClassifier.py --ignore=hicexplorer/test/general/test_hicTrainTADClassifier.py
    displayName: 'Pytest'

  - bash: |
      conda run -n hicexplorer py.test hicexplorer/test/general/test_hicTADClassifier.py
      conda run -n hicexplorer py.test hicexplorer/test/general/test_hicTrainTADClassifier.py
    displayName: 'Pytest TAD Classifier'
