"""Export a workflow to a POSIX shell script or a Snakefile.

Both carry exactly the command lines ``run`` executes, and both run them from
the workdir. The shell script takes an optional first argument that replaces
the workdir recorded at export time.
"""

import json
import os
import re
import shlex

from .cmdline import shell_join
from .model import STATE_DIR
from .plan import make_plans

from .. import __version__


def _header(workflow, comment="#"):
    return "{c} Generated by hicexplorer-workflow {v} from workflow '{n}'.\n".format(
        c=comment, v=__version__, n=workflow.name)


def export_sh(workflow, loader):
    plans = make_plans(workflow, loader)
    lines = ["#!/bin/sh", _header(workflow).rstrip("\n"),
             "# Usage: sh SCRIPT [WORKDIR]  (default: the workdir at export time)",
             "set -eu",
             "WORKDIR=" + shlex.quote(workflow.workdir),
             'if [ "$#" -gt 0 ]; then WORKDIR=$1; fi',
             'cd "$WORKDIR"', ""]
    for step in workflow.topological_order():
        plan = plans[step.id]
        lines.append("# step {} ({}{})".format(step.id, step.tool,
                                               " " + step.subcommand if step.subcommand else ""))
        if plan.mkdirs:
            lines.append("mkdir -p " + shell_join(plan.mkdirs))
        lines.append(plan.command)
        lines.append("")
    return "\n".join(lines)


def rule_name(step_id):
    return "step_" + re.sub(r"[^A-Za-z0-9_]", "_", step_id)


def marker(step_id):
    return "{}/snakemake/{}.done".format(STATE_DIR, step_id)


def _py(text):
    return json.dumps(text)


def export_snakemake(workflow, loader):
    plans = make_plans(workflow, loader)
    order = workflow.topological_order()
    out = [_header(workflow).rstrip("\n"),
           "# Every rule touches a marker file; dependencies between rules go through the markers.",
           "",
           "workdir: " + _py(workflow.workdir),
           "",
           "rule all:",
           "    input:"]
    out.extend("        {},".format(_py(marker(s.id))) for s in order)
    out.append("")
    for step in order:
        plan = plans[step.id]
        out.append("rule {}:".format(rule_name(step.id)))
        inputs = [p for p, _kind in sorted(plan.inputs.items())
                  if os.path.isabs(p) or workflow.producer_of(p) is None]
        inputs += [marker(d) for d in sorted(step.deps, key=lambda d: workflow.step(d).index)]
        if inputs:
            out.append("    input:")
            out.extend("        {},".format(_py(p)) for p in inputs)
        out.append("    output:")
        for name, rel in step.outputs.items():
            kind = plan.output_kind(name)
            if kind == "file":
                out.append("        {},".format(_py(rel)))
            elif kind == "directory":
                out.append("        directory({}),".format(_py(rel)))
            # prefixes cannot be declared; the marker stands for them
        out.append("        touch({}),".format(_py(marker(step.id))))
        out.append("    threads: {}".format(step.threads))
        command = plan.command
        if plan.mkdirs:
            command = "mkdir -p {} && {}".format(shell_join(plan.mkdirs), command)
        out.append("    shell:")
        out.append("        " + _py(command.replace("{", "{{").replace("}", "}}")))
        out.append("")
    return "\n".join(out)
