package:
  name: hicexplorer
  version: '1.7.2'

source:
  path: ../

build:
  number: 0
  skip: True # [not py27]
  script: $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10.4
    - scipy >=0.17.1
    - matplotlib >=1.5.3
    - pysam
    - intervaltree >=2.1.0
    - biopython >=1.65
    - pytables >=3.2.2
    - pybigwig >=0.2.8
    - pandas
    - htslib >=1.3,<1.4
  run:
    - python
    - pybigwig >=0.2.8
    - numpy >=1.10.4
    - scipy >=0.17.1
    - matplotlib >=1.5.3
    - pysam
    - intervaltree >=2.1.0
    - biopython >=1.65
    - pytables >=3.2.2
    - pybigwig >=0.2.8
    - pandas
    - htslib >=1.3,<1.4

test:
  imports:
    - hicexplorer

  commands:
    - hicBuildMatrix --version
    - hicCorrelate --version

about:
  home: https://github.com/maxplanck-ie/HiCExplorer
  license: GPL3
  summary: Set of programs to process, analyze and visualize Hi-C data
