categories:
- Sequence Analysis
- Visualization
description: "HiCExplorer: Set of programs to process, analyze and visualize Hi-C data."
long_description: |
  Sequencing techniques that probe the 3D organization of the genome generate large amounts of
  data whose processing, analysis and visualization is challenging. Here, we present Hi-C Explorer,
  a set of tools for the analysis and visualization of chromosome conformation data. Hi-C explorer
  facilitates the creation of contact matrices, correction of contacts, TAD detection, merging,
  reordering or chromosomes, conversion from different formats and detection of long-range contacts.
  Moreover, it allows the visualization of multiple contact matrices along with other types of data
  like genes, compartments, ChIP-seq coverage tracks (and in general any type of genomic scores) and long range contacts.

  doi: 10.5281/zenodo.159780

  Repository-Maintainer: Björn Grüning

  https://github.com/maxplanck-ie/HiCExplorer
name: hicexplorer
owner: bgruening
remote_repository_url: https://github.com/maxplanck-ie/HiCExplorer/tree/master/galaxy/wrapper/
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for HiCExplorer: {{ tool_name }}"
suite:
  name: "suite_hicexplorer"
  description: "HiCExplorer: Set of programs to process, analyze and visualize Hi-C data."
  long_description: |
    Sequencing techniques that probe the 3D organization of the genome generate large amounts of
    data whose processing, analysis and visualization is challenging. Here, we present Hi-C Explorer,
    a set of tools for the analysis and visualization of chromosome conformation data. Hi-C explorer
    facilitates the creation of contact matrices, correction of contacts, TAD detection, merging,
    reordering or chromosomes, conversion from different formats and detection of long-range contacts.
    Moreover, it allows the visualization of multiple contact matrices along with other types of data
    like genes, compartments, ChIP-seq coverage tracks (and in general any type of genomic scores) and long range contacts.

    doi: 10.5281/zenodo.159780

    Repository-Maintainer: Björn Grüning

    https://github.com/maxplanck-ie/HiCExplorer

