"""Characterization tests for hicInfo.

These tests pin the exact textual output of the current Python implementation
on real test matrices. They exist so that the C++ port in cpp/tools/hicInfo.cpp
can be checked against a fixed reference instead of against a moving target.

Every expected block below was produced by the 3.7.6 Python implementation and
is byte exact including tabs, the thousands separators and the two blank lines
in front of the "Generated by" block of the cooler metadata path.
"""
import warnings
warnings.simplefilter(action="ignore", category=RuntimeWarning)
warnings.simplefilter(action="ignore", category=PendingDeprecationWarning)

import os
from tempfile import NamedTemporaryFile

from hicexplorer import hicInfo
from hicexplorer._version import __version__
from hicexplorer.test.test_compute_function import compute

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "test_data")

LI_COOL = os.path.join(ROOT, 'Li_et_al_2015.cool')
LI_H5 = os.path.join(ROOT, 'Li_et_al_2015.h5')
DTAD = os.path.join(ROOT, 'hicDifferentialTAD')
UNTREATED_COOL = os.path.join(DTAD, 'GSM2644945_Untreated-R1.100000_chr1.cool')
UNTREATED_H5 = os.path.join(DTAD, 'GSM2644945_Untreated-R1.100000_chr1.h5')
AUXIN_COOL = os.path.join(DTAD, 'GSM2644947_Auxin2days-R1.100000_chr1.cool')

HEADER = "# Matrix information file. Created with HiCExplorer's hicInfo version {}\n".format(__version__)


def run_hicInfo(args):
    """Run hicInfo with --outFileName and return the file content."""
    outfile = NamedTemporaryFile(suffix='.txt', delete=False)
    outfile.close()
    compute(hicInfo.main, args + ['--outFileName', outfile.name], 1)
    with open(outfile.name) as file_handle:
        content = file_handle.read()
    os.unlink(outfile.name)
    return content


def expected_li_cool(path=LI_COOL):
    return (HEADER
            + "File:\t{}\n".format(path)
            + "Date:\t2018-11-08T20:03:12.737522\n"
            + "Genome assembly:\tunknown\n"
            + "Size:\t11,104\n"
            + "Chromosomes:length: X: 22422827 bp; \n"
            + "Number of chromosomes:\t1\n"
            + "Non-zero elements:\t1,661,678\n"
            + "The following columns are available: ['chrom' 'start' 'end']\n"
            + "\n\nGenerated by:\tcooler-0.7.11\n")


def expected_li_h5(path=LI_H5, columns_line=''):
    return (HEADER
            + "File:\t{}\n".format(path)
            + "Size:\t11,104\n"
            + "Bin_length:\t1843\n"
            + "Sum of matrix:\t17548966.536917936\n"
            + "Chromosomes:length: X: 22422827 bp; \n"
            + "Non-zero elements:\t3,313,107\n"
            + "Minimum (non zero):\t0.1702102389180371\n"
            + "Maximum:\t1914.0146478655674\n"
            + "NaN bins:\t855\n"
            + columns_line)


def expected_untreated_cool(path=UNTREATED_COOL):
    return (HEADER
            + "File:\t{}\n".format(path)
            + "Date:\t2020-06-29T11:34:45.760096\n"
            + "Genome assembly:\tunknown\n"
            + "Size:\t1,972\n"
            + "Bin_length:\t100000\n"
            + "Chromosomes:length: chr1: 197195432 bp; \n"
            + "Number of chromosomes:\t1\n"
            + "Non-zero elements:\t1,252,980\n"
            + "The following columns are available: ['chrom' 'start' 'end']\n"
            + "\n\nGenerated by:\tHiCMatrix-13\n"
            + "Cooler library version:\tcooler-0.8.6.post0\n"
            + "HiCMatrix url:\thttps://github.com/deeptools/HiCMatrix\n")


def expected_untreated_h5(path=UNTREATED_H5, columns_line=''):
    return (HEADER
            + "File:\t{}\n".format(path)
            + "Size:\t1,972\n"
            + "Bin_length:\t100000\n"
            + "Sum of matrix:\t809.7410356609984\n"
            + "Chromosomes:length: chr1: 197195432 bp; \n"
            + "Non-zero elements:\t2,504,071\n"
            + "Minimum (non zero):\t1.3271409292967762e-05\n"
            + "Maximum:\t0.12034209360197595\n"
            + "NaN bins:\t83\n"
            + columns_line)


def expected_auxin_cool(path=AUXIN_COOL):
    return (HEADER
            + "File:\t{}\n".format(path)
            + "Date:\t2020-06-29T11:34:23.601917\n"
            + "Genome assembly:\tunknown\n"
            + "Size:\t1,972\n"
            + "Bin_length:\t100000\n"
            + "Chromosomes:length: chr1: 197195432 bp; \n"
            + "Number of chromosomes:\t1\n"
            + "Non-zero elements:\t1,466,566\n"
            + "The following columns are available: ['chrom' 'start' 'end']\n"
            + "\n\nGenerated by:\tHiCMatrix-13\n"
            + "Cooler library version:\tcooler-0.8.6.post0\n"
            + "HiCMatrix url:\thttps://github.com/deeptools/HiCMatrix\n")


COLUMNS_LINE = "The following columns are available: ['chrom' 'start' 'end']\n"


def test_cool_metadata():
    """Default path for a cool file: everything is taken from the cooler info."""
    assert run_hicInfo(['-m', LI_COOL]) == expected_li_cool()


def test_cool_metadata_variable_bins_has_no_bin_length():
    """Li_et_al_2015.cool is bin-type 'variable' and stores bin-size 'null'.

    cooler maps that to None, so hicInfo must not print a Bin_length line.
    """
    content = run_hicInfo(['-m', LI_COOL])
    assert 'Bin_length' not in content
    assert 'Sum of matrix' not in content
    assert 'NaN bins' not in content


def test_h5():
    assert run_hicInfo(['-m', LI_H5]) == expected_li_h5()


def test_h5_ignores_no_metadata():
    """H5 always takes the slow path, so -nm must not change anything."""
    assert run_hicInfo(['-m', LI_H5, '-nm']) == expected_li_h5()


def test_cool_no_metadata():
    """-nm loads the matrix through HiCMatrix, exactly like the h5 path.

    The cool and the h5 version of Li_et_al_2015 hold the same matrix, so the
    numbers must be identical; only the trailing column line is added because
    the file is still a cooler file.
    """
    assert run_hicInfo(['-m', LI_COOL, '-nm']) == expected_li_h5(
        path=LI_COOL, columns_line=COLUMNS_LINE)


def test_100kb_cool_metadata():
    assert run_hicInfo(['-m', UNTREATED_COOL]) == expected_untreated_cool()


def test_100kb_h5():
    assert run_hicInfo(['-m', UNTREATED_H5]) == expected_untreated_h5()


def test_100kb_cool_no_metadata():
    assert run_hicInfo(['-m', UNTREATED_COOL, '-nm']) == expected_untreated_h5(
        path=UNTREATED_COOL, columns_line=COLUMNS_LINE)


def test_100kb_auxin_cool_metadata():
    assert run_hicInfo(['-m', AUXIN_COOL]) == expected_auxin_cool()


def test_100kb_auxin_cool_no_metadata():
    """The sum of the symmetric matrix differs from the 'sum' cooler attribute.

    The cooler attribute of this file is 742.3307878299139, while summing the
    lower-triangle-filled matrix gives 742.330787829914. Both are pinned on
    purpose; the difference is pure floating point summation order.
    """
    content = run_hicInfo(['-m', AUXIN_COOL, '-nm'])
    assert content == (HEADER
                       + "File:\t{}\n".format(AUXIN_COOL)
                       + "Size:\t1,972\n"
                       + "Bin_length:\t100000\n"
                       + "Sum of matrix:\t742.330787829914\n"
                       + "Chromosomes:length: chr1: 197195432 bp; \n"
                       + "Non-zero elements:\t2,931,241\n"
                       + "Minimum (non zero):\t7.890892094489899e-06\n"
                       + "Maximum:\t0.08955076886364301\n"
                       + "NaN bins:\t81\n"
                       + COLUMNS_LINE)


def test_several_matrices_outfile_keeps_only_the_last():
    """--outFileName is reopened in 'w' mode per matrix.

    With several matrices the file therefore holds only the block of the last
    matrix. This is a quirk of the 3.7.6 implementation and is pinned here so
    that the port reproduces it.
    """
    content = run_hicInfo(['-m', LI_COOL, LI_H5, UNTREATED_COOL])
    assert content == expected_untreated_cool()


def test_several_matrices_stdout(capsys):
    """-m with several matrices prints the blocks in argument order."""
    hicInfo.main(['-m', LI_COOL, LI_H5, UNTREATED_COOL])
    captured = capsys.readouterr()
    assert captured.out == (expected_li_cool() + '\n'
                            + expected_li_h5() + '\n'
                            + expected_untreated_cool() + '\n')


def test_several_matrices_mixed_no_metadata(capsys):
    hicInfo.main(['-m', UNTREATED_H5, UNTREATED_COOL, '--no_metadata'])
    captured = capsys.readouterr()
    assert captured.out == (expected_untreated_h5() + '\n'
                            + expected_untreated_h5(path=UNTREATED_COOL,
                                                    columns_line=COLUMNS_LINE)
                            + '\n')


def test_stdout(capsys):
    """Without --outFileName the same text is printed, plus print's newline."""
    hicInfo.main(['-m', UNTREATED_H5])
    captured = capsys.readouterr()
    assert captured.out == expected_untreated_h5() + '\n'


def test_stdout_two_matrices(capsys):
    hicInfo.main(['-m', UNTREATED_H5, UNTREATED_COOL])
    captured = capsys.readouterr()
    assert captured.out == (expected_untreated_h5() + '\n'
                            + expected_untreated_cool() + '\n')
